### ISSUE TITLE
Replace duplicate bearer token configuration with Axios interceptor

### ISSUE THREAD

**Issue by wsloth** [meindertduin/PolderjongensFM#21]
I noticed a lot of places containing ``authorization: `Bearer ${context.rootState.oidcStore.access_token}` ``.

These could be replaced by writing one generic axios interceptor which sets the bearer token for every request.

Check out the docs over here: https://github.com/axios/axios#interceptors :)

**Comment by wsloth** [comment]
Oops, never mind, I see that the following:
```js
@Watch('accessToken')
  setAxiosInterceptor(newValue:any, oldValue:any){
      // @ts-ignore
      this.$axios.interceptors.request.use(
              (config:any) => {
                config.headers.common["Authorization"] = `Bearer ${newValue}`;
                config.withCredentials = true;
                return config;
            },        
      )
    this.$store.dispatch('profileModule/getUserProfile');
  }
```

Is already configured in `App.vue`.

Consider removing all the duplicates then, as they will make it hard to maintain this one you want to change anything about authentication.

**Comment by meindertduin** [comment]
Have resolved this issue in commit: [https://github.com/meindertduin/PolderjongensFM/commit/1313943f56f3bdd5c1771b98e4f1c5c678ddda59](url)

Issue was that interceptors applied in `app.vue` don't apply to vuex modules. But by creating a interceptor helper function and initializing it in `main.ts`, interceptors are now applied to both and duplicates could be removed.

Thanks for pointing this out :)
